import React, { Component } from 'react';
import { BrowserRouter, Route } from 'react-router-dom';
import './Event.css';

class Event extends Component {
  render() {
      return (
          <div id="event_Main">
              <center>
          <div id="event_main">
          <h1>
            Events
         </h1> 
         
         <p id="Main">
         Hello Welcome to the Samgatha Events...Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...Hello Welcome to the Samgatha Events...
             </p>

             </div>
             <div className="body">
          <div className="event_cult">
          
                <p >
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                Hello Welcome to the Samgatha Events...
                    </p>
             <h2 id="fest">
              Cultural Fest
          </h2>
          </div>


          <div className="event_cult">
          
          <p>
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...

         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
         Hello Welcome to the Samgatha Events...
             </p>
             <h2 id="fest">
              Tecnical Fest
          </h2>
          </div>
          </div>
          </center>
          </div>
            
        
      );
  }
}

export default Event;